"""Export layer maps as STL + colour-swap instructions or as a 3MF bundle.

The STL is a heightmap mesh generated by marching over the layer_map and
producing two triangles per cell for the top surface plus a flat bottom
and four side walls. For flat geometry this is straightforward; curved
("arched") geometry wraps the heightmap around a cylinder section.

3MF output is a simplified Bambu/Prusa-style bundle: the STL mesh embedded
in the 3MF's OPC container along with a `Metadata/project_settings.config`
and `Metadata/model_settings.config` that declare the filament colours and
swap layers. It is readable by modern slicers as a single object with
per-layer colour hints.
"""

from __future__ import annotations

import io
import json
import struct
import zipfile
from dataclasses import dataclass
from typing import Any, List, Optional, Tuple

import numpy as np

from printers import PrinterProfile, build_layer_change_gcode, get_profile


@dataclass
class GeometrySpec:
    width_mm: float
    height_mm: float
    border_mm: float = 0.0
    mode: str = "flat"          # "flat" | "curved" | "cylindrical" | "disc"
    curve_radius_mm: float = 80  # used when mode == curved/cylindrical
    dome_mm: float = 0.0         # used when mode == disc (gentle dome height)


# ---------------------------------------------------------------------------
# Mesh building
# ---------------------------------------------------------------------------

def _build_vertices(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return (top_vertices, bottom_vertices) shaped (H, W, 3)."""
    h, w = layer_map.shape
    usable_w = geo.width_mm - 2 * geo.border_mm
    usable_h = geo.height_mm - 2 * geo.border_mm

    xs = np.linspace(geo.border_mm, geo.border_mm + usable_w, w)
    ys = np.linspace(geo.border_mm, geo.border_mm + usable_h, h)

    # min thickness = 1 layer so the print is continuous.
    z_top = (np.maximum(layer_map, 1) * layer_height_mm).astype(np.float64)

    if geo.mode in ("flat", "disc"):
        X, Y = np.meshgrid(xs, ys)
        # Disc gets an optional gentle dome bump added to z_top.
        if geo.mode == "disc" and geo.dome_mm > 0:
            cx = geo.border_mm + usable_w / 2.0
            cy = geo.border_mm + usable_h / 2.0
            radius = min(usable_w, usable_h) / 2.0
            if radius > 0:
                rr = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2) / radius
                dome = np.clip(1.0 - rr * rr, 0.0, 1.0) * geo.dome_mm
                z_top = z_top + dome
        top = np.stack([X, Y, z_top], axis=-1)
        bottom = np.stack([X, Y, np.zeros_like(z_top)], axis=-1)
        return top, bottom

    # curved / cylindrical — wrap around Y axis with radius R.
    R = max(10.0, geo.curve_radius_mm)
    theta_span = usable_w / R  # arc length / radius
    if geo.mode == "cylindrical":
        theta_span = 2 * np.pi
    thetas = np.linspace(-theta_span / 2, theta_span / 2, w)
    Y, T = np.meshgrid(ys, thetas, indexing="ij")

    # Top surface pushes outward by z_top, bottom sits at radius R.
    r_top = R + z_top
    top = np.stack([
        r_top * np.sin(T),
        Y,
        r_top * np.cos(T) - R,  # offset so back sits at z = 0
    ], axis=-1)
    bottom = np.stack([
        R * np.sin(T),
        Y,
        R * np.cos(T) - R,
    ], axis=-1)
    return top, bottom


def _disc_valid_mask(h: int, w: int, geo: GeometrySpec) -> np.ndarray:
    """For disc mode, returns a (h, w) bool mask of vertices that lie
    inside the inscribed circle. The circle is centred on the usable
    area and uses the smaller of usable_w/usable_h as the diameter."""
    usable_w = geo.width_mm - 2 * geo.border_mm
    usable_h = geo.height_mm - 2 * geo.border_mm
    cx = geo.border_mm + usable_w / 2.0
    cy = geo.border_mm + usable_h / 2.0
    radius = min(usable_w, usable_h) / 2.0
    xs = np.linspace(geo.border_mm, geo.border_mm + usable_w, w)
    ys = np.linspace(geo.border_mm, geo.border_mm + usable_h, h)
    X, Y = np.meshgrid(xs, ys)
    return ((X - cx) ** 2 + (Y - cy) ** 2) <= (radius * radius)


def _build_mesh(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return vertices (N, 3) and faces (M, 3) as int32 indices."""
    top, bottom = _build_vertices(layer_map, layer_height_mm, geo)
    h, w, _ = top.shape

    verts_top = top.reshape(-1, 3)
    verts_bot = bottom.reshape(-1, 3)
    vertices = np.concatenate([verts_top, verts_bot], axis=0)
    top_offset = 0
    bot_offset = verts_top.shape[0]

    def ti(y, x):
        return top_offset + y * w + x

    def bi(y, x):
        return bot_offset + y * w + x

    # For disc mode, only emit triangles where ALL 4 cell corners are
    # inside the circular mask. The side walls then trace the boundary
    # of that masked region instead of the rectangular outline.
    if geo.mode == "disc":
        valid = _disc_valid_mask(h, w, geo)
        cell_ok = (
            valid[:-1, :-1] & valid[:-1, 1:] & valid[1:, :-1] & valid[1:, 1:]
        )
    else:
        cell_ok = np.ones((h - 1, w - 1), dtype=bool)

    faces: List[Tuple[int, int, int]] = []

    # Top surface (only where cell is valid)
    for y in range(h - 1):
        for x in range(w - 1):
            if not cell_ok[y, x]:
                continue
            a = ti(y, x)
            b = ti(y, x + 1)
            c = ti(y + 1, x + 1)
            d = ti(y + 1, x)
            faces.append((a, b, c))
            faces.append((a, c, d))

    # Bottom surface (reverse winding)
    for y in range(h - 1):
        for x in range(w - 1):
            if not cell_ok[y, x]:
                continue
            a = bi(y, x)
            b = bi(y, x + 1)
            c = bi(y + 1, x + 1)
            d = bi(y + 1, x)
            faces.append((a, c, b))
            faces.append((a, d, c))

    if geo.mode == "disc":
        # Walk every cell-edge where one neighbour is invalid (or off-grid)
        # and add a side wall there. Each edge is parameterised by its
        # two endpoints (vertex indices in the top/bottom grid).
        def add_side_wall(p0, p1, outward_right):
            """Add two triangles forming a quad between top edge (p0,p1)
            and the corresponding bottom edge. Wind so the normal points
            outward."""
            t0, t1 = ti(*p0), ti(*p1)
            b0, b1 = bi(*p0), bi(*p1)
            if outward_right:
                faces.append((t0, b0, b1))
                faces.append((t0, b1, t1))
            else:
                faces.append((t0, b1, b0))
                faces.append((t0, t1, b1))

        for y in range(h - 1):
            for x in range(w - 1):
                if not cell_ok[y, x]:
                    continue
                # Top edge (y, x)-(y, x+1): outside if cell above missing
                if y == 0 or not cell_ok[y - 1, x]:
                    add_side_wall((y, x + 1), (y, x), outward_right=True)
                # Bottom edge (y+1, x)-(y+1, x+1): outside if cell below missing
                if y == h - 2 or not cell_ok[y + 1, x]:
                    add_side_wall((y + 1, x), (y + 1, x + 1), outward_right=True)
                # Left edge (y, x)-(y+1, x): outside if cell left missing
                if x == 0 or not cell_ok[y, x - 1]:
                    add_side_wall((y, x), (y + 1, x), outward_right=True)
                # Right edge (y, x+1)-(y+1, x+1): outside if cell right missing
                if x == w - 2 or not cell_ok[y, x + 1]:
                    add_side_wall((y + 1, x + 1), (y, x + 1), outward_right=True)

        faces_arr = np.array(faces, dtype=np.int32)
        return vertices, faces_arr

    # Four side walls for flat/curved/cylindrical rectangle
    for x in range(w - 1):
        # y=0 edge
        a, b = ti(0, x), ti(0, x + 1)
        c, d = bi(0, x + 1), bi(0, x)
        faces.append((a, d, c))
        faces.append((a, c, b))
        # y=h-1 edge
        a, b = ti(h - 1, x + 1), ti(h - 1, x)
        c, d = bi(h - 1, x), bi(h - 1, x + 1)
        faces.append((a, d, c))
        faces.append((a, c, b))

    for y in range(h - 1):
        # x=0 edge
        a, b = ti(y, 0), ti(y + 1, 0)
        c, d = bi(y + 1, 0), bi(y, 0)
        faces.append((a, b, c))
        faces.append((a, c, d))
        # x=w-1 edge
        a, b = ti(y + 1, w - 1), ti(y, w - 1)
        c, d = bi(y, w - 1), bi(y + 1, w - 1)
        faces.append((a, b, c))
        faces.append((a, c, d))

    faces_arr = np.array(faces, dtype=np.int32)
    return vertices, faces_arr


# ---------------------------------------------------------------------------
# STL (binary) writer
# ---------------------------------------------------------------------------

def write_stl_binary(vertices: np.ndarray, faces: np.ndarray) -> bytes:
    """Write a binary STL file to bytes."""
    header = b"CMYKW Lithophane export".ljust(80, b" ")
    tri_count = faces.shape[0]
    out = io.BytesIO()
    out.write(header)
    out.write(struct.pack("<I", tri_count))

    v = vertices[faces]  # (M, 3, 3)
    # Compute normals
    a, b, c = v[:, 0], v[:, 1], v[:, 2]
    n = np.cross(b - a, c - a)
    mag = np.linalg.norm(n, axis=1, keepdims=True)
    mag[mag == 0] = 1.0
    n = n / mag

    for i in range(tri_count):
        out.write(struct.pack("<fff", *n[i]))
        out.write(struct.pack("<fff", *v[i, 0]))
        out.write(struct.pack("<fff", *v[i, 1]))
        out.write(struct.pack("<fff", *v[i, 2]))
        out.write(struct.pack("<H", 0))
    return out.getvalue()


# ---------------------------------------------------------------------------
# Swap-instruction text + slicer paste-ready snippets
# ---------------------------------------------------------------------------

def _build_slic3r_family_snippet(
    layer_indices: List[int], multi_tool: bool = False
) -> str:
    """Conditional layer-change blocks for PrusaSlicer / SuperSlicer /
    OrcaSlicer / Bambu Studio. Paste into:
        Printer Settings → Custom G-code → Before layer change G-code

    Multi-tool printers emit `T<n>` tool changes (no manual pause);
    single-extruder printers emit `M600` filament-change pauses."""
    if not layer_indices:
        return "; no colour swaps in this print\n"
    if multi_tool:
        parts = [
            f"{{if layer_num == {idx}}}T{slot + 1}{{endif}}"
            for slot, idx in enumerate(layer_indices)
        ]
    else:
        parts = [f"{{if layer_num == {idx}}}M600{{endif}}" for idx in layer_indices]
    return "\n".join(parts) + "\n"


def _build_cura_postprocess_note(
    layer_indices: List[int], filament_names: List[str]
) -> str:
    """Cura doesn't support inline templating, so we tell the user to
    use the built-in 'Filament Change' post-processing script."""
    lines = [
        "; Cura users:",
        ";   Extensions → Post Processing → Modify G-Code → 'Filament Change'",
        ";   Add one entry per row below (layer number, optional retract).",
    ]
    for idx, name in zip(layer_indices, filament_names[1:]):
        lines.append(f";   layer={idx}  → swap to {name}")
    return "\n".join(lines) + "\n"


def _build_marlin_raw_snippet(
    swap_heights_mm: List[float], filament_names: List[str]
) -> str:
    """Raw M600s at known Z values. For users that want to drop them in
    by hand or via a post-processor (e.g. octoprint plugin). The first
    filament is loaded BEFORE the print, so no M600 is needed for it."""
    if len(swap_heights_mm) <= 1:
        return "; no swaps required\n"
    lines = [f"; BASE filament loaded at print start: {filament_names[0]}"]
    for z, name in zip(swap_heights_mm[1:], filament_names[1:]):
        lines.append(f"; Z={z:.3f}mm — load {name}")
        lines.append("M600")
    return "\n".join(lines) + "\n"


def build_swap_instructions(
    swap_heights_mm: List[float],
    swap_colors: List[str],
    filament_names: List[str],
    layer_height_mm: float,
    profile: Optional[PrinterProfile] = None,
) -> str:
    """Generate a paste-ready, multi-slicer swap-instruction document."""
    if profile is None:
        profile = get_profile("generic_orca")
    multi_tool = profile["multi_tool"]

    swap_layer_indices: List[int] = []
    for z in swap_heights_mm[1:]:
        swap_layer_indices.append(max(1, int(round(z / layer_height_mm))))

    lines: List[str] = [
        "; ====================================================================",
        "; CMYKW Lithophane — Colour Swap Instructions",
        f";   printer        = {profile['manufacturer']} {profile['name']}",
        f";   slicer family  = {profile['slicer_family']}",
        f";   swap mechanism = {'tool change (AMS / multi-tool)' if multi_tool else 'M600 manual pause'}",
        f";   layer height   = {layer_height_mm} mm",
        f";   colour swaps   = {len(swap_layer_indices)}",
        "; ====================================================================",
        ";",
        "; ----- Filament load order (bottom -> top) -----",
    ]
    for i, (z, c, name) in enumerate(
        zip(swap_heights_mm, swap_colors, filament_names)
    ):
        marker = "BASE" if i == 0 else f"SWAP {i}"
        lines.append(f";   {marker:<7} Z={z:6.3f}mm  {name:<14} {c}")
    lines.append(";")

    lines.append(
        "; ====================================================================="
    )
    if multi_tool:
        lines.append(
            "; OPTION A — Paste into your slicer's 'Before layer change G-code':"
        )
        lines.append(
            ";   (Multi-tool: T<n> changes AMS lane / extruder — no manual pause)"
        )
    else:
        lines.append(
            "; OPTION A — Paste into your slicer's 'Before layer change G-code':"
        )
        lines.append(
            ";   Works in: PrusaSlicer / SuperSlicer / OrcaSlicer / Bambu Studio"
        )
    lines.append(
        "; ====================================================================="
    )
    lines.append(
        _build_slic3r_family_snippet(swap_layer_indices, multi_tool).rstrip()
    )

    lines.append("")
    lines.append(
        "; ====================================================================="
    )
    lines.append("; OPTION B — Cura (uses post-processing script, not custom G-code):")
    lines.append(
        "; ====================================================================="
    )
    lines.append(
        _build_cura_postprocess_note(swap_layer_indices, filament_names).rstrip()
    )

    lines.append("")
    lines.append(
        "; ====================================================================="
    )
    lines.append("; OPTION C — Raw Marlin G-code (drop in via post-processor):")
    lines.append(
        "; ====================================================================="
    )
    lines.append(_build_marlin_raw_snippet(swap_heights_mm, filament_names).rstrip())
    lines.append("")
    lines.append("; End of swap instructions")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 3MF writer (simplified but slicer-friendly)
# ---------------------------------------------------------------------------

_CONTENT_TYPES = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
    '<Default Extension="config" ContentType="application/vnd.ms-printing.3dmanufacturing-ct-colorcfg+xml"/>'
    '</Types>'
)

_RELS = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>'
    '</Relationships>'
)


def _mesh_to_3mf_model(vertices: np.ndarray, faces: np.ndarray) -> str:
    parts: List[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<model unit="millimeter" xml:lang="en-US" ',
        'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">',
        '<resources>',
        '<object id="1" type="model"><mesh><vertices>',
    ]
    for v in vertices:
        parts.append(f'<vertex x="{v[0]:.4f}" y="{v[1]:.4f}" z="{v[2]:.4f}"/>')
    parts.append('</vertices><triangles>')
    for f in faces:
        parts.append(f'<triangle v1="{f[0]}" v2="{f[1]}" v3="{f[2]}"/>')
    parts.append('</triangles></mesh></object>')
    parts.append('</resources>')
    parts.append(
        '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build>'
    )
    parts.append('</model>')
    return "".join(parts)


def _project_config(
    filaments: List[Tuple[str, str]],
    swap_heights_mm: List[float],
    layer_height_mm: float,
    profile: PrinterProfile,
    license_text: str = "",
) -> str:
    """Bambu/Orca/Prusa-compatible project settings subset.

    Embeds `layer_change_gcode` with the appropriate per-printer flavour:
    `M600` pauses for single-extruder, `T<n>` tool changes for AMS / MMU /
    multi-tool printers. Also tags the project with the printer's name
    and the creator-declared license.
    """
    colours = [c for _, c in filaments]
    names = [n for n, _ in filaments]

    swap_layer_indices: List[int] = []
    for z in swap_heights_mm[1:]:
        swap_layer_indices.append(max(1, int(round(z / layer_height_mm))))
    layer_change_gcode = build_layer_change_gcode(profile, swap_layer_indices)

    cfg: dict[str, Any] = {
        "filament_colour": colours,
        "filament_type": ["PLA"] * len(colours),
        "filament_settings_id": names,
        "layer_height": layer_height_mm,

        # Per-printer auto-swap G-code (M600 vs T<n>).
        "before_layer_change_gcode": layer_change_gcode,
        "layer_change_gcode": layer_change_gcode,

        # Printer + bed metadata so slicers pick the right machine on import.
        "printer_model": profile["name"],
        "printer_manufacturer": profile["manufacturer"],
        "slicer_family": profile["slicer_family"],
        "printable_area": [
            "0x0",
            f"{profile['bed_x_mm']}x0",
            f"{profile['bed_x_mm']}x{profile['bed_y_mm']}",
            f"0x{profile['bed_y_mm']}",
        ],
        "printable_height": profile["max_z_mm"],

        # Reference data for tooling that reads this file.
        "cmykw_swap_heights_mm": swap_heights_mm,
        "cmykw_swap_colors": colours,
        "cmykw_swap_layers": swap_layer_indices,
        "cmykw_multi_tool": profile["multi_tool"],
    }
    if license_text:
        cfg["cmykw_license"] = license_text
    return json.dumps(cfg, indent=2)


def write_3mf(
    vertices: np.ndarray,
    faces: np.ndarray,
    filaments: List[Tuple[str, str]],
    swap_heights_mm: List[float],
    layer_height_mm: float,
    profile: Optional[PrinterProfile] = None,
    license_text: str = "",
) -> bytes:
    """Build a minimal 3MF container with the mesh + colour metadata."""
    if profile is None:
        profile = get_profile("generic_orca")
    model_xml = _mesh_to_3mf_model(vertices, faces)
    project_cfg = _project_config(
        filaments, swap_heights_mm, layer_height_mm, profile, license_text
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", _CONTENT_TYPES)
        z.writestr("_rels/.rels", _RELS)
        z.writestr("3D/3dmodel.model", model_xml)
        z.writestr("Metadata/project_settings.config", project_cfg)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Public helper: build all artefacts
# ---------------------------------------------------------------------------

def build_export(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
    filament_names: List[str],
    swap_heights_mm: List[float],
    swap_colors: List[str],
    printer_id: str = "generic_orca",
    license_text: str = "",
) -> dict:
    profile = get_profile(printer_id)
    vertices, faces = _build_mesh(layer_map, layer_height_mm, geo)
    stl_bytes = write_stl_binary(vertices, faces)
    swap_txt = build_swap_instructions(
        swap_heights_mm, swap_colors, filament_names, layer_height_mm, profile
    )
    filaments = list(zip(filament_names, swap_colors))
    threemf = write_3mf(
        vertices, faces, filaments, swap_heights_mm, layer_height_mm,
        profile, license_text,
    )
    return {
        "stl": stl_bytes,
        "swap_txt": swap_txt.encode("utf-8"),
        "threemf": threemf,
        "triangle_count": int(faces.shape[0]),
        "vertex_count": int(vertices.shape[0]),
        "printer_id": profile["id"],
        "supported_formats": profile["supported_formats"],
    }
