"""Export layer maps as STL + colour-swap instructions or as a 3MF bundle.

The STL is a heightmap mesh generated by marching over the layer_map and
producing two triangles per cell for the top surface plus a flat bottom
and four side walls. For flat geometry this is straightforward; curved
("arched") geometry wraps the heightmap around a cylinder section.

3MF output is a simplified Bambu/Prusa-style bundle: the STL mesh embedded
in the 3MF's OPC container along with a `Metadata/project_settings.config`
and `Metadata/model_settings.config` that declare the filament colours and
swap layers. It is readable by modern slicers as a single object with
per-layer colour hints.
"""

from __future__ import annotations

import io
import json
import struct
import zipfile
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np


@dataclass
class GeometrySpec:
    width_mm: float
    height_mm: float
    border_mm: float = 0.0
    mode: str = "flat"          # "flat" | "curved" | "cylindrical"
    curve_radius_mm: float = 80  # used when mode == curved/cylindrical


# ---------------------------------------------------------------------------
# Mesh building
# ---------------------------------------------------------------------------

def _build_vertices(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return (top_vertices, bottom_vertices) shaped (H, W, 3)."""
    h, w = layer_map.shape
    usable_w = geo.width_mm - 2 * geo.border_mm
    usable_h = geo.height_mm - 2 * geo.border_mm

    xs = np.linspace(geo.border_mm, geo.border_mm + usable_w, w)
    ys = np.linspace(geo.border_mm, geo.border_mm + usable_h, h)

    # min thickness = 1 layer so the print is continuous.
    z_top = (np.maximum(layer_map, 1) * layer_height_mm).astype(np.float64)

    if geo.mode == "flat":
        X, Y = np.meshgrid(xs, ys)
        top = np.stack([X, Y, z_top], axis=-1)
        bottom = np.stack([X, Y, np.zeros_like(z_top)], axis=-1)
        return top, bottom

    # curved / cylindrical — wrap around Y axis with radius R.
    R = max(10.0, geo.curve_radius_mm)
    theta_span = usable_w / R  # arc length / radius
    if geo.mode == "cylindrical":
        theta_span = 2 * np.pi
    thetas = np.linspace(-theta_span / 2, theta_span / 2, w)
    Y, T = np.meshgrid(ys, thetas, indexing="ij")

    # Top surface pushes outward by z_top, bottom sits at radius R.
    r_top = R + z_top
    top = np.stack([
        r_top * np.sin(T),
        Y,
        r_top * np.cos(T) - R,  # offset so back sits at z = 0
    ], axis=-1)
    bottom = np.stack([
        R * np.sin(T),
        Y,
        R * np.cos(T) - R,
    ], axis=-1)
    return top, bottom


def _build_mesh(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return vertices (N, 3) and faces (M, 3) as int32 indices."""
    top, bottom = _build_vertices(layer_map, layer_height_mm, geo)
    h, w, _ = top.shape

    verts_top = top.reshape(-1, 3)
    verts_bot = bottom.reshape(-1, 3)
    vertices = np.concatenate([verts_top, verts_bot], axis=0)
    top_offset = 0
    bot_offset = verts_top.shape[0]

    def ti(y, x):
        return top_offset + y * w + x

    def bi(y, x):
        return bot_offset + y * w + x

    faces: List[Tuple[int, int, int]] = []

    # Top surface
    for y in range(h - 1):
        for x in range(w - 1):
            a = ti(y, x)
            b = ti(y, x + 1)
            c = ti(y + 1, x + 1)
            d = ti(y + 1, x)
            faces.append((a, b, c))
            faces.append((a, c, d))

    # Bottom surface (reverse winding so normals face down/inward)
    for y in range(h - 1):
        for x in range(w - 1):
            a = bi(y, x)
            b = bi(y, x + 1)
            c = bi(y + 1, x + 1)
            d = bi(y + 1, x)
            faces.append((a, c, b))
            faces.append((a, d, c))

    # Four side walls
    for x in range(w - 1):
        # y=0 edge
        a, b = ti(0, x), ti(0, x + 1)
        c, d = bi(0, x + 1), bi(0, x)
        faces.append((a, d, c))
        faces.append((a, c, b))
        # y=h-1 edge
        a, b = ti(h - 1, x + 1), ti(h - 1, x)
        c, d = bi(h - 1, x), bi(h - 1, x + 1)
        faces.append((a, d, c))
        faces.append((a, c, b))

    for y in range(h - 1):
        # x=0 edge
        a, b = ti(y, 0), ti(y + 1, 0)
        c, d = bi(y + 1, 0), bi(y, 0)
        faces.append((a, b, c))
        faces.append((a, c, d))
        # x=w-1 edge
        a, b = ti(y + 1, w - 1), ti(y, w - 1)
        c, d = bi(y, w - 1), bi(y + 1, w - 1)
        faces.append((a, b, c))
        faces.append((a, c, d))

    faces_arr = np.array(faces, dtype=np.int32)
    return vertices, faces_arr


# ---------------------------------------------------------------------------
# STL (binary) writer
# ---------------------------------------------------------------------------

def write_stl_binary(vertices: np.ndarray, faces: np.ndarray) -> bytes:
    """Write a binary STL file to bytes."""
    header = b"CMYKW Lithophane export".ljust(80, b" ")
    tri_count = faces.shape[0]
    out = io.BytesIO()
    out.write(header)
    out.write(struct.pack("<I", tri_count))

    v = vertices[faces]  # (M, 3, 3)
    # Compute normals
    a, b, c = v[:, 0], v[:, 1], v[:, 2]
    n = np.cross(b - a, c - a)
    mag = np.linalg.norm(n, axis=1, keepdims=True)
    mag[mag == 0] = 1.0
    n = n / mag

    for i in range(tri_count):
        out.write(struct.pack("<fff", *n[i]))
        out.write(struct.pack("<fff", *v[i, 0]))
        out.write(struct.pack("<fff", *v[i, 1]))
        out.write(struct.pack("<fff", *v[i, 2]))
        out.write(struct.pack("<H", 0))
    return out.getvalue()


# ---------------------------------------------------------------------------
# Swap-instruction text
# ---------------------------------------------------------------------------

def build_swap_instructions(
    swap_heights_mm: List[float],
    swap_colors: List[str],
    filament_names: List[str],
    layer_height_mm: float,
) -> str:
    lines = [
        "# CMYKW Lithophane — Colour Swap Instructions",
        f"# layer_height_mm = {layer_height_mm}",
        "# Load filaments in this order bottom → top.",
        "#",
    ]
    for z, c, name in zip(swap_heights_mm, swap_colors, filament_names):
        layer_idx = int(round(z / layer_height_mm))
        lines.append(
            f"M600 ; swap to {name} ({c}) at Z={z:.3f}mm (layer {layer_idx})"
        )
    lines.append("# End of swap instructions")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 3MF writer (simplified but slicer-friendly)
# ---------------------------------------------------------------------------

_CONTENT_TYPES = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
    '<Default Extension="config" ContentType="application/vnd.ms-printing.3dmanufacturing-ct-colorcfg+xml"/>'
    '</Types>'
)

_RELS = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>'
    '</Relationships>'
)


def _mesh_to_3mf_model(vertices: np.ndarray, faces: np.ndarray) -> str:
    parts: List[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<model unit="millimeter" xml:lang="en-US" ',
        'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">',
        '<resources>',
        '<object id="1" type="model"><mesh><vertices>',
    ]
    for v in vertices:
        parts.append(f'<vertex x="{v[0]:.4f}" y="{v[1]:.4f}" z="{v[2]:.4f}"/>')
    parts.append('</vertices><triangles>')
    for f in faces:
        parts.append(f'<triangle v1="{f[0]}" v2="{f[1]}" v3="{f[2]}"/>')
    parts.append('</triangles></mesh></object>')
    parts.append('</resources>')
    parts.append(
        '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build>'
    )
    parts.append('</model>')
    return "".join(parts)


def _project_config(
    filaments: List[Tuple[str, str]],
    swap_heights_mm: List[float],
    layer_height_mm: float,
) -> str:
    """Bambu-compatible project settings subset."""
    colours = [c for _, c in filaments]
    names = [n for n, _ in filaments]
    cfg = {
        "filament_colour": colours,
        "filament_type": ["PLA"] * len(colours),
        "filament_settings_id": names,
        "layer_height": layer_height_mm,
        "cmykw_swap_heights_mm": swap_heights_mm,
        "cmykw_swap_colors": colours,
    }
    return json.dumps(cfg, indent=2)


def write_3mf(
    vertices: np.ndarray,
    faces: np.ndarray,
    filaments: List[Tuple[str, str]],
    swap_heights_mm: List[float],
    layer_height_mm: float,
) -> bytes:
    """Build a minimal 3MF container with the mesh + colour metadata."""
    model_xml = _mesh_to_3mf_model(vertices, faces)
    project_cfg = _project_config(filaments, swap_heights_mm, layer_height_mm)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", _CONTENT_TYPES)
        z.writestr("_rels/.rels", _RELS)
        z.writestr("3D/3dmodel.model", model_xml)
        z.writestr("Metadata/project_settings.config", project_cfg)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Public helper: build both
# ---------------------------------------------------------------------------

def build_export(
    layer_map: np.ndarray,
    layer_height_mm: float,
    geo: GeometrySpec,
    filament_names: List[str],
    swap_heights_mm: List[float],
    swap_colors: List[str],
) -> dict:
    vertices, faces = _build_mesh(layer_map, layer_height_mm, geo)
    stl_bytes = write_stl_binary(vertices, faces)
    swap_txt = build_swap_instructions(
        swap_heights_mm, swap_colors, filament_names, layer_height_mm
    )
    filaments = list(zip(filament_names, swap_colors))
    threemf = write_3mf(vertices, faces, filaments, swap_heights_mm, layer_height_mm)
    return {
        "stl": stl_bytes,
        "swap_txt": swap_txt.encode("utf-8"),
        "threemf": threemf,
        "triangle_count": int(faces.shape[0]),
        "vertex_count": int(vertices.shape[0]),
    }
